# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bEDn8cdKTFGEN3ftdEMgz0zujvQFJQhn

**CS312 Assignment 01**  *Sagar Deware (202051166)*
"""

pip install pandas

import pandas as pd
import json

"""Question NO 01"""

#Reading the file using read function
csvFile = pd.read_csv('district_level_service_msme.csv')
#Printing the File Which was Read.
print (csvFile)

# Alloting the File to f
f = open(r"district_level_manufacturing_msme.json")
# Loading the file as data
data=json.load(f)
# Defining columns
coloumns=pd.DataFrame(data["fields"])["label"].tolist()
jsonFile=pd.DataFrame(data["data"],columns=coloumns)
#printing the jsonfile
print(jsonFile)

"""Question No. 02"""

# Defining the data type and size
jsonFile["SMALL"] = jsonFile["SMALL"].astype('int64')
print("The Small Manufacturing MSME in India State wise\n") 
# printing the selected small coloumn
print(jsonFile["SMALL"])
#Printing the Sum of Total Small manu. MSME
print("The total Small Manufacturing MSME in INDIA ", jsonFile["SMALL"].sum())

"""Question No. 03"""

# Grouping by State with Total Count
csvState=csvFile.groupby("STATE_NAME").sum() 
# Selecting the columns in csvState
csvState2=csvState[["MICRO","SMALL","MEDIUM"]]
# Printing the selected columns
print(csvState2)
# Saving the File in csv extension
csvState2.to_csv(r'C:\Users\sagar deware\Downloads\RESULT.csv')

"""Quesion No. 04"""

# Renaming the columns of both files
csvFile.rename(columns={'MICRO': 'MICRO_y', 'SMALL': 'SMALL_y', 'MEDIUM': 'MEDIUM_y', 'Total': 'Total_y'}, inplace=True)
jsonFile.rename(columns={'MICRO': 'MICRO_x', 'SMALL': 'SMALL_x', 'MEDIUM': 'MEDIUM_x', 'Total': 'Total_x'}, inplace=True)

# Defining Data type and size of every coloumn
jsonFile["Lg_Dist_Code"] = jsonFile["Lg_Dist_Code"].astype('int64')
jsonFile["MICRO_x"] = jsonFile["MICRO_x"].astype('int64')
jsonFile["SMALL_x"] = jsonFile["SMALL_x"].astype('int64')
jsonFile["MEDIUM_x"] = jsonFile["MEDIUM_x"].astype('int64')
jsonFile["Total_x"] = jsonFile["Total_x"].astype('int64')

# merging both files
mergeFile=pd.merge(jsonFile,csvFile)

# printing merged file
print (mergeFile)

"""Queston No. 05"""

# Grouping the mergred file by state with their total count
mergeFileState=mergeFile.groupby("STATE_NAME").sum()
# selecting the coloumn 
mergeFileState2=mergeFileState[["MEDIUM_x","MEDIUM_y","MICRO_x","MICRO_y","SMALL_x","SMALL_y"]]
# selecting coloumn for pivot table
mergeFileState2.pivot_table(index='STATE_NAME')