# -*- coding: utf-8 -*-
"""Assignment5b_CS_202051166.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xaaYZmOM2oU0nHl2OYcnRJhp7eUNOV9S

**Lab Assignment 05b**

**Sagar Deware(202051166)**
"""

!pip install joypy
!pip install squarify
!pip install plotly

import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import transforms
from statsmodels.graphics.mosaicplot import mosaic
from joypy import joyplot #!pip install joypy
import squarify # pip install squarify
import plotly.express as px # pip install plotly

Heart_csv = pd.read_csv("heart.csv")
Heart_csv.head()

updated_csv = Heart_csv[Heart_csv["thal"] >= 3]

sns.scatterplot(
    data = updated_csv, x="cp", y="age",
    sizes = (20, 200), legend="full"
)

fig = sns.PairGrid(updated_csv[["age", "sex", "cp", "trestbps", "slope"]])
fig.map(sns.scatterplot)

fig = px.parallel_categories(Heart_csv, dimensions=['sex', 'cp',   'fbs',   'slope', 'ca', 'thal','target'], color="age", color_continuous_scale=px.colors.sequential.Plasma)
fig.show()