# -*- coding: utf-8 -*-
"""Assignment6_CS_202051166.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oHJvHxOLJz4O6J1MOzWsbWIGLuTDNqwA

Lab Assignment 06

Sagar Deware (202051166)
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

female_csv = pd.read_csv('population_of_female.csv')

female_csv.head()

completion_rate_file = pd.read_csv('primary_completion_rate_female.csv')

completion_rate_file.head()

completion_rate_file.columns

completion_rate_over_years = completion_rate_file[['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021']]

completion_rate_over_years.head()

"""### Task 1
Create a column named “average_rate” in “primary_completion_rate_female.csv” that
contains the average (over time) completion rate.
"""

completion_rate_file['average_rate'] =completion_rate_over_years.mean(axis=1)

completion_rate_file.head()

female_csv.head()

"""### Task 2
Create a column named “Latest Population” in “population_of_female.csv” that contains the
latest population of females in the country.

Latest population of women will the population of women in the year 2021
"""

female_csv['latest_population'] = female_csv['2021']

female_csv.head()

"""### Task 3
What is the weighted average of primary rates of different countries? The weight should be the
Latest population of females in the country.
"""

completion_rate_file.head(2)

weights = female_csv['latest_population']/female_csv['latest_population'].sum()

#weighted mean
# ((weight * average_rate)/weight.sum()).sum

## note: Sum of weights is always going to be 1
wt_mean = completion_rate_file['average_rate'] * weights
temp_mean = wt_mean/weights.sum()
weighted_mean = temp_mean.sum()
weighted_mean

#weighted median
# step 1: sort the array
sorted_rate = completion_rate_file.sort_values('average_rate')

# step 2: 
wgtsum = 0

for idx,df in sorted_rate.iterrows():
    wgtsum += weights[idx]
    if wgtsum >= 0.5:
        print(df)
        weighted_median = df['average_rate']
        break

print(weighted_median)